### ISSUE TITLE
3x NeoMatrix 8x8 

### ISSUE THREAD

**Issue by AlfMueller** [macetech/FastLED-XY-Map-Generator#1]
I have 3 8x8 matrixes which I would like to put together, could you set the starting point to 65 - 128?

**Comment by marmilicious** [comment]
What if you generate the code for a width 8 by height 24 matrix, and then manually cut/paste to shuffle around the lines in the resulting table?

Here's a example for three 2x2 matrixes, so initially do a 2x6 and get this XYtable:
  const uint8_t XYTable[] = {
     0,   1,
     2,   3,
     4,   5,
     6,   7,
     8,   9,
    10,  11
  };

Then manually cut/paste like:
  const uint8_t XYTable[] = {
     0,   1,        4,   5,        8,   9,
     2,   3,        6,   7,       10,  11
  };

Does that work, or did I reverse something in my brain?

Having an "offset" option, where a starting number could be entered for the first pixel, and it would count up from there instead of zero could be a nice addition too.

**Comment by macegr** [comment]
If the matrices are actually 8x8 squares (without oddly shaped corners or internal holes) then this tool is not really that useful; it's much easier to map the matrices to LED numbers using a small amount of math rather than a big arbitrary const table.
